name: XAUUSD Sinyal Botu

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı UTC
  workflow_dispatch:

jobs:
  run-xauusd-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Reposu klonla
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Gereken kütüphaneleri yükle
      run: |
        pip install pandas requests

    - name: Botu çalıştır
      run: python sinyal_analiz_xauusd.py