name: XAUUSD Sinyal Botu (No GUI)

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı (UTC)
  workflow_dispatch:

jobs:
  run-xauusd-sinyal:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v3

    - name: Python ortamını ayarla
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Gereksinimleri yükle
      run: |
        pip install requests pandas

    - name: Sinyal botunu çalıştır
      run: python sinyal_analiz_xauusd.py